@file:Suppress("DEPRECATION")

package com.example.compose

import com.varabyte.kobweb.compose.ui.graphics.Color
import com.varabyte.kobweb.compose.ui.graphics.Colors


val md_theme_light_primary = Color.rgba(0xFF6750A4.toInt())
/*
val md_theme_light_onPrimary = Colors.rgb(0xFFFFFFFF)
val md_theme_light_primaryContainer = Colors.rgb(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Colors.rgb(0xFF21005D)
val md_theme_light_secondary = Colors.rgb(0xFF625B71)
val md_theme_light_onSecondary = Colors.rgb(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Colors.rgb(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Colors.rgb(0xFF1D192B)
val md_theme_light_tertiary = Colors.rgb(0xFF7D5260)
val md_theme_light_onTertiary = Colors.rgb(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Colors.rgb(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Colors.rgb(0xFF31111D)
val md_theme_light_error = Colors.rgb(0xFFB3261E)
val md_theme_light_onError = Colors.rgb(0xFFFFFFFF)
val md_theme_light_errorContainer = Colors.rgb(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Colors.rgb(0xFF410E0B)
val md_theme_light_outline = Colors.rgb(0xFF79747E)
val md_theme_light_background = Colors.rgb(0xFFFFFBFE)
val md_theme_light_onBackground = Colors.rgb(0xFF1C1B1F)
val md_theme_light_surface = Colors.rgb(0xFFFFFBFE)
val md_theme_light_onSurface = Colors.rgb(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Colors.rgb(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Colors.rgb(0xFF49454F)
val md_theme_light_inverseSurface = Colors.rgb(0xFF313033)
val md_theme_light_inverseOnSurface = Colors.rgb(0xFFF4EFF4)
val md_theme_light_inversePrimary = Colors.rgb(0xFFD0BCFF)
val md_theme_light_shadow = Colors.rgb(0xFF000000)
val md_theme_light_surfaceTint = Colors.rgb(0xFF6750A4)
val md_theme_light_outlineVariant = Colors.rgb(0xFFCAC4D0)
val md_theme_light_scrim = Colors.rgb(0xFF000000)

val md_theme_dark_primary = Colors.rgb(0xFFD0BCFF)
val md_theme_dark_onPrimary = Colors.rgb(0xFF381E72)
val md_theme_dark_primaryContainer = Colors.rgb(0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Colors.rgb(0xFFEADDFF)
val md_theme_dark_secondary = Colors.rgb(0xFFCCC2DC)
val md_theme_dark_onSecondary = Colors.rgb(0xFF332D41)
val md_theme_dark_secondaryContainer = Colors.rgb(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Colors.rgb(0xFFE8DEF8)
val md_theme_dark_tertiary = Colors.rgb(0xFFEFB8C8)
val md_theme_dark_onTertiary = Colors.rgb(0xFF492532)
val md_theme_dark_tertiaryContainer = Colors.rgb(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Colors.rgb(0xFFFFD8E4)
val md_theme_dark_error = Colors.rgb(0xFFF2B8B5)
val md_theme_dark_onError = Colors.rgb(0xFF601410)
val md_theme_dark_errorContainer = Colors.rgb(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Colors.rgb(0xFFF9DEDC)
val md_theme_dark_outline = Colors.rgb(0xFF938F99)
val md_theme_dark_background = Colors.rgb(0xFF1C1B1F)
val md_theme_dark_onBackground = Colors.rgb(0xFFE6E1E5)
val md_theme_dark_surface = Colors.rgb(0xFF1C1B1F)
val md_theme_dark_onSurface = Colors.rgb(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Colors.rgb(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Colors.rgb(0xFFCAC4D0)
val md_theme_dark_inverseSurface = Colors.rgb(0xFFE6E1E5)
val md_theme_dark_inverseOnSurface = Colors.rgb(0xFF313033)
val md_theme_dark_inversePrimary = Colors.rgb(0xFF6750A4)
val md_theme_dark_shadow = Colors.rgb(0xFF000000)
val md_theme_dark_surfaceTint = Colors.rgb(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Colors.rgb(0xFF49454F)
val md_theme_dark_scrim = Colors.rgb(0xFF000000)


val seed = Colors.rgb(0xFF6750A4)
*/